filter:
    paths:
        - 'src/*'
        - 'tests/*'
    excluded_paths:
        - 'vendor/*'
before_commands:
    - 'composer install'
tools:
    php_code_coverage:
        filter:
            paths: ['src/*']
            excluded_paths: ['vendor/*']
        test_command: 'phpunit tests/'
