filter:
    paths:
        - 'src/*'
        - 'tests/*'
    excluded_paths:
        - 'vendor/*'
before_commands:
    - 'composer install'
tools:
    php_cs_fixer:
        filter:
            paths: ['src/*']
            excluded_paths: ['vendor/*']
    php_code_coverage:
        config_path: tests/
        filter:
            paths: ['src/*']
            excluded_paths: ['vendor/*']
    php_cpd:
        filter:
            paths: ['src/*']
            excluded_paths: ['vendor/*']
    php_loc: true
