language: php

services: mongodb

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mkdir log
  - cp config/default.php.dist config/default.php
  - phpenv config-add config.ini
  - composer install -v

script: phpunit tests

